version: "3.8"
services:
  cmr:
  build: ./cmr
  ports: 
    - "8085:8085"
  depends_on:
      - sqlite-db
  environment:
    - DATABASE_URL=/db/yourdb.sqlite
  volumes:
    - ./restaurantData:/db

  sqlite-db:
    build: .
    volumes:
      - ./restaurantData:/db
    stdin_open: true
    tty: true 
